### ISSUE TITLE
Solicitud para procesar fotos

### ISSUE THREAD

**Issue by angoca** [OSM-Colombia/OrtoDrone#1]
*¿Cuántos vuelos desea procesar?*
2

**Comment by TheLudway** [comment]
Tu usuario de OSM cumple con la experiencia para esa cantidad de vuelos (más info en link).

**Comment by TheLudway** [comment]
Procesa este conjunto de fotos (url). Tienes hasta el 29 de septiembre para procesar. Avísame cuando termines de procesar las fotos

**Comment by angoca** [comment]
Hola, ya procesé las fotos, ¿cuándo nos podríamos para validarlas y después publicarlas?

**Comment by TheLudway** [comment]
¿Qué tal estás el 30 de septiembre o el 1 de octubre a la 1pm en ambas fechas?

**Comment by angoca** [comment]
Listo, el 1 de octubre a la 1 pm me queda bien.

**Comment by TheLudway** [comment]
Vale, nos encontramos aquí 
https://osmvideo.cloud68.co/user/col-ibs-rmw-9uu

**Comment by TheLudway** [comment]
Resultado:
La ortofoto está bien pero falta el reporte

**Comment by angoca** [comment]
Aquí te adjunto el reporte. Gracias.

**Comment by TheLudway** [comment]
LGTM!
Ya se puede autorizar el pago, te llegará al cierre del mes. Llena el siguiente formulario para el pago de las fotos del mes (link) y envíalo al siguiente correo: ortodrone@osm.lat
